name: Go
on: push

jobs:

  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    services:
      icinga:
        image: jordan/icinga2
        ports:
          - 8080:80
          - 5665:5665
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download
  
      - name: Get running containers
        run: docker container ps
      
      - name: Get Icinga API Password
        run: |
          echo "ICINGA2_API_PASSWORD=$(docker exec icinga2 bash -c 'grep password /etc/icinga2/conf.d/api-users.conf' | awk -F'"' '{ print $$2}')" >> $GITHUB_OUTPUT
        id: icinga_pass

      - name: Run tests
        run: go test -v -coverprofile=coverage.txt ./...
        env:
          ICINGA_API_PASSWORD: ${{ steps.icinga_pass.outputs.ICINGA_API_PASSWORD }}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
