name: Go
on: push

jobs:

  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    services:
      icinga:
        image: jordan/icinga2
        ports:
          - 8080:80
          - 5665:5665
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download
  
      - name: Get container ID
        run: echo "CONTAINER_ID=$(docker ps --format '{{.Names}}')" >> $GITHUB_OUTPUT
        id: container_id

      - name: Sleep 60s for icinga to setup
        run: sleep 60s
      
      - name: Get Icinga API Password
        run: docker exec $CONTAINER_ID bash -c 'grep password /etc/icinga2/conf.d/api-users.conf' | tr -d ' "' >> $GITHUB_OUTPUT
        id: icinga_pass
        env:
          CONTAINER_ID: ${{ steps.container_id.outputs.CONTAINER_ID }}

      - name: Run tests
        run: go test -v -coverprofile=coverage.txt ./...
        env:
          ICINGA2_API_PASSWORD: ${{ steps.icinga_pass.outputs.password }}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
